# Course states
COURSES_MANAGEMENT, COURSE_MANAGEMENT, EDIT_COURSE_CODE, \
    EDIT_COURSE_TITLE, EDIT_COURSE_LINK, REMOVE_COURSE_REQUEST, \
    REMOVE_COURSE, ADD_COURSE_TITLE, ADD_COURSE_CODE, \
    ADD_COURSE_LINK, ADD_COURSE = map(chr, range(11))

# Test states
TESTS_MANAGEMENT, ADDING_TEST, TEST_MANAGEMENT, EDIT_FUTURE_TEST, \
    EDIT_TEST_TITLE, EDIT_TEST_TAG, REMOVE_TEST_REQUEST, REMOVE_TEST, \
    SEND_SCORES, REUPLOAD_TEST, START_TEST, ACTIVE_TEST_MANAGEMENT, \
    ADD_EXTRA_TIME, FINALIZE_TEST, SEND_MESSAGE_REQUEST, \
    SEND_MESSAGE = map(chr, range(12, 28))

STUDENT_MENU = map(chr, range(29, 30))

JOIN_COURSE_REQUEST, UNKNOWN_COURSE_TAG, UNAVAILABLE_COURSE, JOINED_COURSE, \
    ALREADY_JOINED, COURSE_MENU, TESTS_MENU, SEND_QUESTION, TEST_SCORE, \
    NOT_TAKEN_TEST, WAIT_TEST_FINISH, SUBMIT_HW_REQUEST, SUBMIT_HW, \
    SUBMITED_HW = map(chr, range(31, 45))

# HW (course) states
HWS_MANAGEMENT, ADD_HW_TITLE, ADD_HW_TAG, ADD_DEADLINE, \
    ADD_HW, ADDED_HW, HW_MANAGEMENT, HW_INFO = map(chr, range(46, 54))

SWITCH_COURSE_STATUS = chr(55)

TEST_GRADE, TEST_SAVE_GRADE, HW_GRADE, HW_SAVE_GRADE = map(chr, range(56, 60))

SEND_ANSWERS, SENT_ANSWERS = map(chr, range(61, 63))

COURSE_STUDENTS, COURSE_STUDENT, KICK_STUDENT, \
EDIT_STUDENT_NAME, SAVE_STUDENT_NAME = map(chr, range(64, 69))

EDIT_HW_DEADLINE, SAVE_HW_DEADLINE, EDIT_HW_TITLE, SAVE_HW_TITLE, \
REMOVE_HW = map(chr, range(70, 75))

COMMENT_HW_REQUEST, SEND_HW_COMMENT, HW_MENU, HW_COMMENT = \
    map(chr, range(76, 80))

ADD_TEACHER_NAME, ADD_TEACHER_USERNAME, ADD_TEACHER_ID, ADD_TEACHER = \
    map(chr, range(81, 85))

UPLOAD_SCORES_TEST, UPLOADING_SCORES_TEST, UPLOAD_SCORES_HW,\
UPLOADING_SCORES_HW, REMOVE_TEST, DOWNLOAD_HW_SOLUTIONS = \
    map(chr, range(86, 92))